### ISSUE TITLE
Migrate issues from drupal.org

### ISSUE THREAD

**Issue by rcross** [klausi/pareviewsh#4]
Was trying to do a little friendly issue queue cleaning and figured the issues from https://www.drupal.org/project/issues/pareviewsh has been migrated here already, but I don't see them. 

Would it be helpful to move them over here and then close the others as duplicate on d.o?

**Comment by klausi** [comment]
Thanks!

There are not that many issues, so I'm fine with leaving them where they currently are.

**Comment by rcross** [comment]
Ok, no worries!
